spec-version: 0.36.0
name: Aperiodic
version: 0.1.0
synopsis: Aperiodic
description: An incremental generator for arbitrarily large patches of aperiodic tilings
category: Math

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

default-extensions:
  - LambdaCase
  - FunctionalDependencies
  - DeriveFunctor
  - RecordWildCards

dependencies:
  - base >= 4.13 && < 5
  - containers >= 0.6 && < 1
  - kexc >= 0.1

library:
  source-dirs: src
  exposed-modules:
    - Geometry
    - Substitution
    - Automata
    - Kleenex
    - Tilings.Penrose
    - Tilings.Spectre

executable:
  main: Main.hs
  source-dirs: .
  dependencies:
    - Aperiodic
    - diagrams-core >= 1.4 && < 2
    - diagrams-lib >= 1.4 && < 2
    - diagrams-svg >= 1.4 && < 2
    - colour >= 2.3 && < 3
